gExchange.Web/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using gExchange.Web.Helpers;
using gExchange.Web.Service;
using gExchange.Web.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace gExchange.Web.Controllers
{
    [AuthorizationAttribute(admin: true, user: true)]
    public class ItemController : Controller
    {
        readonly IItemService _itemService;

        public ItemController(IItemService itemService)
        {
            _itemService = itemService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            ItemVM item = _itemService.getById(id);
            return View("Details", item);
        }

        public IActionResult GetItems()
        {
            RowsVM<ItemVM> items = _itemService.getAll();
            return PartialView("_listPartial", items);
        }

        public IActionResult GetItem()
        {
            return PartialView("_addPartial", new ItemVM());
        }

        [HttpPost]
        public async Task<JsonResult> CreateItem(ItemVM item)
        {
            
            try
            {
                if (!ModelState.IsValid)
                {
                    string messages = string.Join("; ", ModelState.Values
                                        .SelectMany(x => x.Errors)
                                        .Select(x => x.ErrorMessage));
                    throw new Exception("Please correct the following errors: " + Environment.NewLine + messages);
                }
                UserVM user = HttpContext.GetLoggedUser();
                await _itemService.add(item, user.Id);

                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    }
}

gExchange.Web/Controllers/UserController.cs
using System.IO;
using System.Threading.Tasks;
using gExchange.Web.Helpers;
using gExchange.Web.Service;
using gExchange.Web.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace gExchange.Web.Controllers
{
    [AuthorizationAttribute(admin: true, user:true)]
    public class UserController : Controller
    {
        readonly IUserService _userService;
        readonly IImageService _imageService;

        public UserController(IUserService userService, IImageService imageService)
        {
            _userService = userService;
            _imageService = imageService;
        }
        
        public ActionResult Index()
        {
            RowsVM<UserVM> userRows = _userService.getUsers();
            return View("Index", userRows);
        }

        public ViewResult Add()
        {
            var model = new UserVM();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(UserVM user)
        {
            // Dodavanje fajla
            if (ModelState.IsValid)
            {
                IFormFile file = (HttpContext.Request.Form.Files.Count > 0) ? HttpContext.Request.Form.Files[0] : null;
                await _imageService.Save(file);
            }

            // Stari code
            await _userService.addUser(user);
            return RedirectToAction("Index");
        }

        public ViewResult Edit(int id)
        {
            var model = _userService.getById(id);
            return View("Add", model);
        }

        public ViewResult Delete(int id)
        {
            var model = _userService.getById(id);
            return View("Delete", model);
        }

        [HttpPost]
        public IActionResult DeleteItem(int id)
        {
            _userService.deleteUser(id);
            return RedirectToAction("Index");
        }

        public IActionResult Profile()
        {
            UserVM user = HttpContext.GetLoggedUser();
            UserVM model = _userService.getByAndMessages(user.Id);
            return View("Profile", model);
        }
    }
}

gExchange.Web/Views/Shared/_Layout.cshtml
@using gExchange.Web.ViewModel
@using gExchange.Web.Helpers
@using Microsoft.AspNetCore.Http

@{ UserVM user = Context.GetLoggedUser(); }

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - gExchange.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Goodies Exchange</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">Items</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        @if (user != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Profile">

                                    <label style="color: dodgerblue">

                                        @user.FirstName
                                        @user.LastName
                                    </label>
                                </a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">
                                @if (user != null)
                                {
                                    <label style="color: orangered">
                                        Logout
                                    </label> 
                                }
                                else
                                {
                                    <label>
                                        Login
                                    </label>
                                }
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">
                                Signup
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Goodies Exchange  - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

gExchange.Web/Views/Shared/_LayoutAnonim.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Goodies Exchange</title>

    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="/css/site.css" />


    <script src="/lib/jquery/dist/jquery.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>

    <script src="/js/site.js"></script>

</head>
<body>

    @RenderBody()



</body>
</html>